name: Test
on: [push]
jobs:
  Test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch:
          - aarch64-linux
          - aarch64-darwin
    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579

      - name: Setup
        uses: ./setup
        with:
          tailscaleAuthKey: ${{ secrets.TAILSCALE_AUTHKEY }}
          nixBuildSshKey: ${{ secrets.NIX_BUILD_SSH_KEY }}
          nixCacheS3AccessKeyId: ${{ secrets.NIX_CACHE_S3_ACCESS_KEY_ID }}
          nixCacheS3SecretAccessKey: ${{ secrets.NIX_CACHE_S3_SECRET_ACCESS_KEY }}

      - name: Build
        uses: ./build
        with:
          nixOutput: .#defaultPackage.${{ matrix.arch }}

      - run: cat ./result

      - run: |
          tailscale status
          sudo tailscale logout

      - name: Cache
        uses: ./cache
        with:
          nixOutput: .#defaultPackage.${{ matrix.arch }}
          nixCachePrivateKey: ${{ secrets.NIX_CACHE_PRIVATE_KEY }}
